'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class WinFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gesalt.WinFormStrings", GetType(WinFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connection Error.
        '''</summary>
        Friend Shared ReadOnly Property conError() As String
            Get
                Return ResourceManager.GetString("conError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connection established successfully.
        '''</summary>
        Friend Shared ReadOnly Property conOK() As String
            Get
                Return ResourceManager.GetString("conOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Thing.
        '''</summary>
        Friend Shared ReadOnly Property Cosa() As String
            Get
                Return ResourceManager.GetString("Cosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No connection bd..
        '''</summary>
        Friend Shared ReadOnly Property csNotFound() As String
            Get
                Return ResourceManager.GetString("csNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The database will change. The data saved in the old one will not be saved in the new one. The program will stop and the next time you run it, it will open with the new database..
        '''</summary>
        Friend Shared ReadOnly Property dbChange() As String
            Get
                Return ResourceManager.GetString("dbChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Database change.
        '''</summary>
        Friend Shared ReadOnly Property dbChangeTitle() As String
            Get
                Return ResourceManager.GetString("dbChangeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a An error occurred while trying to connect to the database. Check the connection settings..
        '''</summary>
        Friend Shared ReadOnly Property dbErrorMsg() As String
            Get
                Return ResourceManager.GetString("dbErrorMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Check the connection settings.
        '''</summary>
        Friend Shared ReadOnly Property dbErrorTitle() As String
            Get
                Return ResourceManager.GetString("dbErrorTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a An error occurred while connecting to the database. The program will stop and the next time you run it, the wizard will open to check if the connection data is correct..
        '''</summary>
        Friend Shared ReadOnly Property fatalErrorDB() As String
            Get
                Return ResourceManager.GetString("fatalErrorDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fatal error.
        '''</summary>
        Friend Shared ReadOnly Property fatalErrorDBTitle() As String
            Get
                Return ResourceManager.GetString("fatalErrorDBTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gesalt is running for the first time. You must enter some data..
        '''</summary>
        Friend Shared ReadOnly Property firstTimeMsg() As String
            Get
                Return ResourceManager.GetString("firstTimeMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Setup Wizard.
        '''</summary>
        Friend Shared ReadOnly Property firstTimeTitle() As String
            Get
                Return ResourceManager.GetString("firstTimeTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gesalt.
        '''</summary>
        Friend Shared ReadOnly Property msgTitle() As String
            Get
                Return ResourceManager.GetString("msgTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You must choose a database location.
        '''</summary>
        Friend Shared ReadOnly Property noDBMsg() As String
            Get
                Return ResourceManager.GetString("noDBMsg", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
